/**
 * Manifest schema validator — the runtime authority for `moq-media-corpus/1`.
 *
 * Returns a list of human-readable problems (empty ⇒ valid). Purely structural:
 * it does NOT touch the filesystem (hashes / lengths / containment are the
 * loader's job). It DOES enforce the canonical-encoding rules that are schema
 * concerns — chiefly that every wide-integer field is a decimal string, never a
 * JSON number.
 *
 * @module
 */

import {
  CORPUS_SCHEMA,
  VECTOR_KINDS,
  WIRE_PROFILES,
  STAGES,
  STATUSES,
  PROVENANCE_CLASSES,
  EXPECTATION_BASES,
  DIFFERENTIAL_STATUSES,
  ERROR_CATEGORIES,
  BMFF_OPERATIONS,
  isFileInput,
  isPropertyMapInput,
  type CorpusEntry,
  type DomainManifest,
  type ExpectBlock,
} from './schema-types.js';

const ID_SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*(?:\/[a-z0-9]+(?:-[a-z0-9]+)*)+$/;
const SHA256 = /^[0-9a-f]{64}$/;
const HEX = /^(?:[0-9a-f]{2})*$/;
const U64_DECIMAL = /^(?:0|[1-9][0-9]*)$/; // unsigned, no sign, no leading zeros
const MAX_U64 = 18446744073709551615n;
const INT32_MAX = 2147483647;
const INT32_MIN = -2147483648;

const ALLOWED_ENTRY_KEYS = new Set([
  'id', 'kind', 'profile', 'wireProfile', 'scope', 'operation', 'description',
  'input', 'expect', 'expectationBasis', 'provenance', 'differential', 'retired',
]);

/** A canonical unsigned-64-bit decimal STRING in [0, 2^64-1] (never a JSON number). */
function isU64String(v: unknown): v is string {
  if (typeof v !== 'string' || !U64_DECIMAL.test(v)) return false;
  try {
    const n = BigInt(v);
    return n >= 0n && n <= MAX_U64;
  } catch {
    return false;
  }
}

/**
 * Recursively reject floats and out-of-int32 JSON numbers anywhere in a
 * projection: the corpus bans floats, and any integer wider than int32 must be
 * a decimal string (so it survives JSON round-trips losslessly).
 */
function checkNumericSanity(p: Problems, path: string, val: unknown): void {
  if (typeof val === 'number') {
    if (!Number.isInteger(val)) p.at(path, 'floats are prohibited in the corpus');
    else if (val > INT32_MAX || val < INT32_MIN) p.at(path, 'an integer outside int32 must be a decimal STRING (wide-int rule)');
  } else if (Array.isArray(val)) {
    val.forEach((v, i) => checkNumericSanity(p, `${path}[${i}]`, v));
  } else if (val !== null && typeof val === 'object') {
    for (const [k, v] of Object.entries(val)) checkNumericSanity(p, `${path}.${k}`, v);
  }
}

class Problems {
  readonly list: string[] = [];
  at(path: string, msg: string): void {
    this.list.push(`${path}: ${msg}`);
  }
}

function checkProvenance(p: Problems, path: string, prov: unknown): void {
  if (typeof prov !== 'object' || prov === null) {
    p.at(path, 'provenance must be an object');
    return;
  }
  const o = prov as Record<string, unknown>;
  if (!PROVENANCE_CLASSES.includes(o['class'] as never)) p.at(`${path}.class`, `must be one of ${PROVENANCE_CLASSES.join('|')}`);
  for (const f of ['source', 'section', 'generator', 'generatorVersion', 'command']) {
    if (typeof o[f] !== 'string' || (o[f] as string).length === 0) p.at(`${path}.${f}`, 'must be a non-empty string');
  }
  // sourceHash is ALWAYS a real SHA-256, never a placeholder: the cited draft for
  // spec-derived, the tool output for third-party, the generated bytes for
  // implementation-generated. Enforced identically here and in the JSON Schema.
  if (!SHA256.test(String(o['sourceHash']))) {
    p.at(`${path}.sourceHash`, 'must be a 64-char SHA-256 of the cited source');
  }
}

function checkExpect(p: Problems, path: string, expect: unknown, allowedStages: readonly string[]): void {
  if (typeof expect !== 'object' || expect === null) {
    p.at(path, 'expect must be an object');
    return;
  }
  const e = expect as ExpectBlock & Record<string, unknown>;
  if (!STATUSES.includes(e.status as never)) p.at(`${path}.status`, `must be one of ${STATUSES.join('|')}`);
  if (!STAGES.includes(e.stage as never)) p.at(`${path}.stage`, `must be one of ${STAGES.join('|')}`);
  else if (!allowedStages.includes(e.stage)) p.at(`${path}.stage`, `stage "${e.stage}" not allowed for this kind (allowed: ${allowedStages.join('|')})`);

  if (e.status === 'error') {
    if (typeof e.error !== 'object' || e.error === null) p.at(`${path}.error`, 'required when status is "error"');
    else {
      if (!ERROR_CATEGORIES.includes(e.error.category as never)) p.at(`${path}.error.category`, `must be a known error category, got ${JSON.stringify(e.error.category)}`);
      if (e.error.note !== undefined && typeof e.error.note !== 'string') p.at(`${path}.error.note`, 'must be a string');
    }
    // An error result carries ONLY an error — no output payloads.
    if (e.semantics !== undefined) p.at(`${path}.semantics`, 'must be absent when status is "error"');
    if (e.bytesHex !== undefined) p.at(`${path}.bytesHex`, 'must be absent when status is "error"');
    if (e.canonicalHex !== undefined) p.at(`${path}.canonicalHex`, 'must be absent when status is "error"');
  } else if (e.status === 'ok') {
    if (e.error !== undefined) p.at(`${path}.error`, 'must be absent when status is "ok"');
    if (e.stage === 'encode') {
      // Encode produces bytes ONLY.
      if (typeof e.bytesHex !== 'string' || !HEX.test(e.bytesHex)) p.at(`${path}.bytesHex`, 'encode+ok requires canonical lowercase-hex bytes');
      if (e.semantics !== undefined) p.at(`${path}.semantics`, 'must be absent for an encode-direction result');
      if (e.canonicalHex !== undefined) p.at(`${path}.canonicalHex`, 'must be absent for an encode-direction result');
    } else {
      // Decode/semantic produce a projection ONLY (canonicalHex allowed on decode).
      if (e.semantics === undefined) p.at(`${path}.semantics`, 'required when status is "ok" and stage is decode/semantic');
      if (e.bytesHex !== undefined) p.at(`${path}.bytesHex`, 'must be absent for a decode/semantic result');
      if (e.stage === 'semantic' && e.canonicalHex !== undefined) p.at(`${path}.canonicalHex`, 'canonicalHex applies only to the decode direction');
    }
  }

  if (e.canonicalHex !== undefined && (typeof e.canonicalHex !== 'string' || !HEX.test(e.canonicalHex))) {
    p.at(`${path}.canonicalHex`, 'must be canonical lowercase hex');
  }
  // Ban floats / out-of-int32 numbers anywhere in the projection.
  if (e.semantics !== undefined) checkNumericSanity(p, `${path}.semantics`, e.semantics);
  if (e.diagnostics !== undefined) {
    if (!Array.isArray(e.diagnostics) || !e.diagnostics.every((d) => typeof d === 'string')) {
      p.at(`${path}.diagnostics`, 'must be an array of strings');
    } else {
      const sorted = [...e.diagnostics].sort();
      if (!e.diagnostics.every((d, i) => d === sorted[i])) p.at(`${path}.diagnostics`, 'must be sorted');
    }
  }
}

function checkInput(p: Problems, path: string, entry: CorpusEntry): void {
  const input = entry.input as unknown;
  if (typeof input !== 'object' || input === null) {
    p.at(path, 'input must be an object');
    return;
  }
  const hasFile = 'file' in (input as object);
  const hasPropertyMap = 'propertyMap' in (input as object);
  if (hasFile === hasPropertyMap) {
    p.at(path, 'input must have exactly one of "file" or "propertyMap"');
    return;
  }
  if (hasFile && isFileInput(entry.input)) {
    const fi = entry.input;
    if (typeof fi.file !== 'string' || fi.file.length === 0) p.at(`${path}.file`, 'must be a non-empty string');
    if (typeof fi.file === 'string' && (fi.file.includes('..') || fi.file.startsWith('/'))) p.at(`${path}.file`, 'must be a plain relative filename (no ".." or absolute path)');
    if (typeof fi.byteLength !== 'number' || !Number.isInteger(fi.byteLength) || fi.byteLength < 0) p.at(`${path}.byteLength`, 'must be a non-negative integer');
    if (typeof fi.sha256 !== 'string' || !SHA256.test(fi.sha256)) p.at(`${path}.sha256`, 'must be a 64-char lowercase hex sha256');
    const isBin = typeof fi.file === 'string' && fi.file.endsWith('.bin');
    if (fi.hex !== undefined) {
      if (typeof fi.hex !== 'string' || !HEX.test(fi.hex)) p.at(`${path}.hex`, 'must be canonical lowercase hex');
      else if (fi.hex.length / 2 !== fi.byteLength) p.at(`${path}.hex`, `hex length ${fi.hex.length / 2} does not match byteLength ${fi.byteLength}`);
    } else if (isBin && typeof fi.byteLength === 'number' && fi.byteLength <= 512) {
      p.at(`${path}.hex`, 'mandatory for *.bin inputs of 512 bytes or fewer');
    }
  } else if (hasPropertyMap && isPropertyMapInput(entry.input)) {
    const pm = entry.input.propertyMap;
    if (!Array.isArray(pm)) {
      p.at(`${path}.propertyMap`, 'must be an array');
    } else {
      pm.forEach((e, i) => {
        const ep = `${path}.propertyMap[${i}]`;
        if (!isU64String(e?.id)) p.at(`${ep}.id`, 'must be an unsigned decimal-string u64 in [0, 2^64-1] (not a JSON number, not signed)');
        if (e?.valueKind !== 'varint' && e?.valueKind !== 'bytes') p.at(`${ep}.valueKind`, 'must be "varint" or "bytes"');
        if (e?.valueKind === 'varint' && !isU64String(e?.value)) p.at(`${ep}.value`, 'varint value must be an unsigned decimal-string u64 in [0, 2^64-1]');
        if (e?.valueKind === 'bytes' && (typeof e?.value !== 'string' || !HEX.test(e.value))) p.at(`${ep}.value`, 'bytes value must be canonical lowercase hex');
      });
    }
  }
}

/**
 * Validate one corpus entry. Returns problem strings (empty ⇒ valid).
 */
export function validateEntry(entry: unknown, path = 'entry'): string[] {
  const p = new Problems();
  if (typeof entry !== 'object' || entry === null) {
    p.at(path, 'must be an object');
    return p.list;
  }
  const e = entry as CorpusEntry & Record<string, unknown>;

  // Exact keys: reject any unknown top-level property.
  for (const k of Object.keys(e)) {
    if (!ALLOWED_ENTRY_KEYS.has(k)) p.at(`${path}.${k}`, 'unknown property (exact keys enforced)');
  }

  if (typeof e.id !== 'string' || !ID_SLUG.test(e.id)) p.at(`${path}.id`, 'must be a stable slug like "domain/name" (lowercase, hyphen/slash)');

  // Tombstone: a retired vector is inert — only id + retired are validated.
  if (e.retired !== undefined) {
    if (typeof e.retired !== 'object' || e.retired === null || typeof (e.retired as { reason?: unknown }).reason !== 'string') {
      p.at(`${path}.retired`, 'must be { reason: string }');
    }
    return p.list;
  }
  if (!VECTOR_KINDS.includes(e.kind as never)) p.at(`${path}.kind`, `must be one of ${VECTOR_KINDS.join('|')}`);
  if (typeof e.profile !== 'string' || e.profile.length === 0) p.at(`${path}.profile`, 'must be a non-empty string');
  if (typeof e.description !== 'string' || e.description.length === 0) p.at(`${path}.description`, 'must be a non-empty string');
  if (!EXPECTATION_BASES.includes(e.expectationBasis as never)) p.at(`${path}.expectationBasis`, `must be one of ${EXPECTATION_BASES.join('|')}`);

  // Kind-discriminated required/forbidden fields.
  const byteLevelProperty = e.kind === 'property-block-decode' || e.kind === 'loc-properties';
  if (byteLevelProperty) {
    if (!WIRE_PROFILES.includes(e.wireProfile as never)) p.at(`${path}.wireProfile`, `required for ${e.kind}; must be one of ${WIRE_PROFILES.join('|')}`);
  } else if (e.wireProfile !== undefined) {
    p.at(`${path}.wireProfile`, `must be absent for ${e.kind}`);
  }

  const isLoc = e.kind === 'loc-properties' || e.kind === 'loc-semantics';
  if (e.scope !== undefined && e.scope !== 'track' && e.scope !== 'object') p.at(`${path}.scope`, 'must be "track" or "object"');
  if (e.scope !== undefined && !isLoc) p.at(`${path}.scope`, `must be absent for ${e.kind}`);

  // The operation under test is part of the INPUT contract (never derived from
  // expected output). Required for bmff-structure, forbidden elsewhere.
  if (e.kind === 'bmff-structure') {
    if (!BMFF_OPERATIONS.includes(e.operation as never)) p.at(`${path}.operation`, `required for bmff-structure; must be one of ${BMFF_OPERATIONS.join('|')}`);
  } else if (e.operation !== undefined) {
    p.at(`${path}.operation`, `must be absent for ${e.kind}`);
  }

  // Allowed stages + input shape per kind.
  let allowedStages: readonly string[] = STAGES;
  switch (e.kind) {
    case 'property-block-decode':
      allowedStages = ['decode', 'encode'];
      break;
    case 'loc-semantics':
      allowedStages = ['semantic'];
      break;
    case 'loc-properties':
      allowedStages = ['decode', 'semantic', 'encode']; // encode = the property-block encode driver
      break;
    case 'catalog-parse':
    case 'catalog-delta-parse':
    case 'bmff-structure':
    case 'msfts-validate':
      allowedStages = ['decode', 'semantic'];
      break;
  }
  checkExpect(p, `${path}.expect`, e.expect, allowedStages);
  checkInput(p, `${path}.input`, e as CorpusEntry);

  // Direction ⇒ input shape (explicit, never inferred): encode uses propertyMap,
  // decode/semantic-from-bytes use a file, loc-semantics uses propertyMap.
  const stage = (e.expect as ExpectBlock | undefined)?.stage;
  const hasFile = typeof e.input === 'object' && e.input !== null && 'file' in (e.input as object);
  const hasPm = typeof e.input === 'object' && e.input !== null && 'propertyMap' in (e.input as object);
  if (e.kind === 'loc-semantics' && !hasPm) p.at(`${path}.input`, 'loc-semantics requires a propertyMap input');
  if (e.kind === 'property-block-decode' || e.kind === 'loc-properties') {
    // Encode direction takes a propertyMap; decode/semantic take a byte file.
    if (stage === 'encode' && !hasPm) p.at(`${path}.input`, `${e.kind} with stage "encode" requires a propertyMap input`);
    if ((stage === 'decode' || stage === 'semantic') && !hasFile) p.at(`${path}.input`, `${e.kind} with stage "${stage}" requires a file input`);
  }
  if ((e.kind === 'catalog-parse' || e.kind === 'catalog-delta-parse' || e.kind === 'bmff-structure' || e.kind === 'msfts-validate') && !hasFile) {
    p.at(`${path}.input`, `${e.kind} requires a file input`);
  }

  checkProvenance(p, `${path}.provenance`, e.provenance);

  if (e.differential !== undefined) {
    if (typeof e.differential !== 'object' || e.differential === null) p.at(`${path}.differential`, 'must be an object keyed by implementation');
    else {
      for (const [impl, d] of Object.entries(e.differential as Record<string, unknown>)) {
        const dp = `${path}.differential.${impl}`;
        if (typeof d !== 'object' || d === null) { p.at(dp, 'must be an object'); continue; }
        const de = d as Record<string, unknown>;
        if (!DIFFERENTIAL_STATUSES.includes(de['status'] as never)) p.at(`${dp}.status`, `must be one of ${DIFFERENTIAL_STATUSES.join('|')}`);
        if ((de['status'] === 'diverges' || de['status'] === 'unimplemented')) {
          if (de['currentBehavior'] === undefined) p.at(`${dp}.currentBehavior`, `mandatory for status "${de['status']}"`);
          else checkExpect(p, `${dp}.currentBehavior`, de['currentBehavior'], STAGES);
        } else if (de['currentBehavior'] !== undefined) {
          p.at(`${dp}.currentBehavior`, `must be absent for status "${de['status'] as string}" (only diverges/unimplemented record it)`);
        }
        if (de['reason'] !== undefined && typeof de['reason'] !== 'string') p.at(`${dp}.reason`, 'must be a string');
      }
    }
  }

  return p.list;
}

/**
 * Validate a whole domain manifest, including id uniqueness across the manifest.
 */
export function validateManifest(manifest: unknown, path = 'manifest'): string[] {
  const p = new Problems();
  if (typeof manifest !== 'object' || manifest === null) {
    p.at(path, 'must be an object');
    return p.list;
  }
  const m = manifest as DomainManifest & Record<string, unknown>;
  if (m.corpusSchema !== CORPUS_SCHEMA) p.at(`${path}.corpusSchema`, `must be "${CORPUS_SCHEMA}"`);
  if (typeof m.domain !== 'string' || m.domain.length === 0) p.at(`${path}.domain`, 'must be a non-empty string');
  if (m.note !== undefined && typeof m.note !== 'string') p.at(`${path}.note`, 'must be a string');
  if (!Array.isArray(m.vectors)) {
    p.at(`${path}.vectors`, 'must be an array');
    return p.list;
  }
  const seen = new Set<string>();
  m.vectors.forEach((v, i) => {
    for (const problem of validateEntry(v, `${path}.vectors[${i}]`)) p.list.push(problem);
    const id = (v as CorpusEntry)?.id;
    if (typeof id === 'string') {
      if (seen.has(id)) p.at(`${path}.vectors[${i}].id`, `duplicate id "${id}"`);
      seen.add(id);
    }
  });
  return p.list;
}
