/**
 * Synthetic in-memory fixture, shaped EXACTLY like the documented on-disk contract
 * (fixtures/README.md): same track set, same metadata fields, same
 * one-chunk-per-object flow. The only difference is where the bytes come from —
 * a future disk loader produces this same `LoadedFixture` from real CMAF files,
 * and the publisher won't change.
 *
 * Payloads are track-distinct and identify their group/object so the smoke can
 * assert routing precisely: "synthetic:<track>/g<group>/chunk-<NNN>" + filler.
 */
// The canonical in-memory shapes (LoadedFixture/LoadedTrack) live in fixture.ts —
// this module just CONSTRUCTS that shape from generated bytes.
import type { FixtureTrack, LoadedTrack, LoadedFixture } from './fixture.js';

const te = new TextEncoder();

export const SYNTH_NAMESPACE = ['demo'] as const;
export const CHUNKS_PER_TRACK = 4;

/** Deterministic, track-distinct fake chunk payload (identifies group + object). */
export const syntheticChunkPayload = (track: string, groupId: bigint, index: number): Uint8Array =>
  te.encode(`synthetic:${track}/g${groupId}/chunk-${String(index).padStart(3, '0')};` + 'x'.repeat(64));

/** Fake init segment: an ftyp-ish prefix + track name (track-distinct, NOT real MP4). */
const syntheticInit = (track: string): Uint8Array => {
  const tag = te.encode(`ftypSYNTH:${track}`);
  const buf = new Uint8Array(4 + tag.length);
  buf.set([0x00, 0x00, 0x00, buf.length], 0); // box-size-looking prefix
  buf.set(tag, 4);
  return buf;
};

const TRACK_METAS: readonly FixtureTrack[] = [
  { name: 'video-1080', packaging: 'cmaf', role: 'video', codec: 'avc1.640028', width: 1920, height: 1080, framerate: 30, bitrate: 6_000_000, init: 'init.mp4', chunks: [] },
  { name: 'video-720', packaging: 'cmaf', role: 'video', codec: 'avc1.64001f', width: 1280, height: 720, framerate: 30, bitrate: 3_000_000, init: 'init.mp4', chunks: [] },
  { name: 'video-360', packaging: 'cmaf', role: 'video', codec: 'avc1.64001e', width: 640, height: 360, framerate: 30, bitrate: 800_000, init: 'init.mp4', chunks: [] },
  { name: 'audio-en', packaging: 'cmaf', role: 'audio', codec: 'mp4a.40.2', samplerate: 48_000, channelConfig: '2', init: 'init.mp4', chunks: [] },
  { name: 'audio-es', packaging: 'cmaf', role: 'audio', codec: 'mp4a.40.2', samplerate: 48_000, channelConfig: '2', init: 'init.mp4', chunks: [] },
];

/** Build the synthetic fixture (catalog metadata + fake init/chunk bytes). */
export function loadSyntheticFixture(): LoadedFixture {
  const chunkNames = Array.from({ length: CHUNKS_PER_TRACK }, (_, i) => `chunk-${String(i).padStart(3, '0')}.m4s`);
  const tracks: LoadedTrack[] = TRACK_METAS.map((meta) => ({
    meta: { ...meta, chunks: chunkNames },
    initData: syntheticInit(meta.name),
    chunks: chunkNames.map((_, i) => syntheticChunkPayload(meta.name, 0n, i)),
  }));
  return {
    manifest: {
      namespace: SYNTH_NAMESPACE,
      renderGroup: 1,
      chunkDurationMs: 500,
      tracks: tracks.map((t) => t.meta),
    },
    tracks,
  };
}
